compress: false
data_path: sample_data/sample_input.csv
disp_length_min: 1
emoCols:
- valence
filter: true
hb_type: SPK10
idCol: idCol
iden: bookNovels
level: 0.68
lex_path: lexicons/NRC-VAD-Lexicon.csv
min_tokens: 5
min_turns: 1
rollingWindow: 5
save_dir: sample_data/novel_outputs/
stopword_path: lexicons/stopwords.txt
stopwords: true
textCol: text
textIdCol: utteranceId
timeCol: Turn
